name: whishful-study

on:
  schedule:
    - cron: '0 23 * * 3,6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4 requests
          pip install pytz

      - name: Run STUDY Notice
        run: python actions/study_notice.py
        env:
          TIL_WEBHOOK_URL: ${{ secrets.TIL_WEBHOOK_URL }}
